vich_uploader:
    db_driver: orm        # or mongodb or phpcr - default db driver
    metadata:
        type: attribute
    mappings:
        profilepics:
            uri_prefix: '/uploads/profilepics'
            upload_destination: '%kernel.project_dir%/public/%profilepics%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        formationimg:
            uri_prefix: '/uploads/formationimg'
            upload_destination: '%kernel.project_dir%/public/%formationimg%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer